name: Build and Deploy
on:
  push:
    tags:
    - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install flyctl cli
      uses: superfly/flyctl-actions/setup-flyctl@master

    - name: Deploy ${{ GITHUB_REF#refs/*/ }} to Fly
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      run: |
        flyctl deploy --remote-only
