name: Deploy to Fly
on:
  push:
    tags:
    - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Setup
      id: setup
      uses: superfly/flyctl-actions/setup-flyctl@master
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
      run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
    - name: Deploy
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        RELEASE_VERSION: ${{ steps.setup.outputs.tag }}
      run: |
        echo "Deploying ${{ github.workspace }} $RELEASE_VERSION to Fly"
        flyctl deploy --remote-only
