name: Deploy to Fly
on:
  push:
    tags:
    - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  
    - id: get_tag
      run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
    - uses: superfly/flyctl-actions/setup-flyctl@master
    - name: Deploy
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        RELEASE_VERSION: ${{ steps.get_tag.outputs.tag }}
      run: |
        echo "Deploying ${{ github.workspace }} $RELEASE_VERSION to Fly"
        flyctl deploy --remote-only
