name: Build and Deploy
on:
  push:
    tags:
    - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install flyctl cli
      uses: superfly/flyctl-actions/setup-flyctl@master

    - name: Set release version
      id: release
      run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      
    - env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        RELEASE_VERSION: ${{ steps.release.outputs.tag }}
      name: Deploy ${{ env.RELEASE_VERSION }} to Fly
      run: |
        flyctl deploy --remote-only
